---
apiVersion: apps/v1
kind: Daemonset
metadata:
  name: kubelet-log-exporter
  namespace: kube-system
  labels:
    app.kubernetes.io/name: node-kubelet-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-kubelet-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-kubelet-exporter
    spec:
      tolerations:
      - operator: Exists # we should export everywhere we can run
      volumes:
      - hostPath:
          path: "/"
          type: ""
        name: host-root
      containers:
      - image: localhost:5001/exporter:latest
        name: exporter
        volumeMounts:
        - mountPath: /host
          name: host-root
